import html
import re

SPORTS_NEWS_URL = "https://t.me/sports_news_ua"

_ALLOWED_TAG_RE = re.compile(r"</?(?:b|i)>", re.IGNORECASE)


def _safe_telegram_html(text: str) -> str:
    """Escape arbitrary HTML while preserving only <b> and <i> generated by the editor."""
    raw = (text or "").strip()
    if not raw:
        return ""

    placeholders: dict[str, str] = {}

    def keep_tag(match: re.Match) -> str:
        key = f"__TG_TAG_{len(placeholders)}__"
        tag = match.group(0).lower()
        placeholders[key] = tag
        return key

    protected = _ALLOWED_TAG_RE.sub(keep_tag, raw)
    escaped = html.escape(protected)
    for key, tag in placeholders.items():
        escaped = escaped.replace(key, tag)
    return escaped


def post_html(text: str) -> str:
    body = _safe_telegram_html(text)
    footer = f'<a href="{SPORTS_NEWS_URL}"><b>SPORTS NEWS</b></a> → на зв’язку.'
    return f"{body}\n\n{footer}" if body else footer


def post_plain(text: str) -> str:
    body = re.sub(r"</?(?:b|i)>", "", (text or "").strip(), flags=re.IGNORECASE)
    footer = "SPORTS NEWS → на зв’язку."
    return f"{body}\n\n{footer}" if body else footer
