SOURCES = [
    "maguairovych", "bfootballua", "v1latsports", "byi_bizhy", "zoryalondonsk",
    "vzbirna", "zabarnoyu", "ukrainechelsea", "yiksperg", "footballconstructor",
    "upl_ua_official", "lateral_footbalI", "lateralbox1ng", "news_blues", "breakevens",
    "bluesche", "tg_chelsea_news", "chelsea_londons", "bitc2306", "beautyCFC",
    "lookAtFacts", "isportualive", "sportsuspilne", "football24ua", "Ukr_football_UA",
    "ukrsportbase", "liverpoolfc_ua", "moya_kalitka", "tatotake_ua", "bombardyr_ua",
    "DynamoKyiv", "v1lat", "olsior", "boikovoice", "GianlucaLapadula",
    "LapadulaNews", "arsenal_ukraine", "chelsea_bridge", "comentatorska", "overtime_sazhko",
    "sctr31", "elfutbolico", "TransferNewsUA", "fcpolissya", "fcshakhtar_news",
    "lateral_cs", "FootbaIl_Time", "viscabarcaua", "lateralfootball", "TIMI_1010",
    "kharkiv_pfc", "targunik", "lookatfootbik", "we_are_chelsea", "chelseafcrus",
    "englishaccent", "telingaterEPL", "tg_epl", "chelsea_tg_news1", "chelseafc365",
    "fabrizio_transfery", "dyra_tv", "footballuaonline", "sportarena_com", "footballandartemfrankov",
    "sportvukr", "setantaukraine", "burbuzz", "TennisUa", "ynwateam",
    "juventusUA", "realmadrid_ukr", "eurofootballpodcast", "this_isamerica", "futbolni_istorii",
    "lapadulabet", "ForzaMilan_ua", "juveleggria", "football_Italy", "wearethearsenal",
    "uefa_conference_league_tg", "AllezFrance",
]
