SOURCES = [
    "bfootballua",
    "v1latsports",
    "byi_bizhy",
    "lateral_box1ng",
    "breakevens",
    "sportsuspilne",
    "tatotake_ua",
    "bombardyr_ua",
    "v1lat",
    "lateral_cs",
    "FootbaIl_Time",
    "tg_epl",
    "sportvukr",
    "TennisUa",
]
